### PR TITLE
Cleanup interfaces

### PR DESCRIPTION
**Pull request by MikeHathaway**
# Cleanup interfaces
## High level
* Remove underscores from event signatures in the Grant Fund's interfaces. This provides consistency with the interface styling of the Pool contracts.
* Sync interface signature with implementation signature for `forge docs`.
* Use named return variable in `updateSlate` to match other external functions.
* No business logic or test changes.

### CODE REVIEW

**Comment by grandizzy** [comment]
Just learned that interface and impl naming should be the same for ` forge doc` to properly render, see in contracts repo pr to fix forge docs

**Comment by MikeHathaway** [comment]
> Just learned that interface and impl naming should be the same for ` forge doc` to properly render, see in contracts repo pr to fix forge docs

Updated to ensure naming matched for `forge doc`

**Review by grandizzy — APPROVED** [review]
lgtm

**Review by ith-harvey — APPROVED** [review]
LGTM

**Pull request merged**
