### PR TITLE
TOB-AJNA-1: Solidity compiler optimizations can be problematic

### PR DESCRIPTION
**Pull request by grandizzy**
- remove optimizer and optimizer runs
Contract size before
```
| Contract          | Size (kB) | Margin (kB) |
|-------------------|-----------|-------------|
| GrantFund         | 19.147    | 5.429       |
```

Contract size after
```
| Contract          | Size (kB) | Margin (kB) |
|-------------------|-----------|-------------|
| GrantFund         | 18.955    | 5.621      |
```

gas before
```
| Function Name                               | min             | avg    | median | max    | # calls |
| claimDelegateReward                         | 1459            | 57888  | 58733  | 65533  | 260     |
| executeExtraordinary                        | 7363            | 42048  | 39841  | 95859  | 10      |
| executeStandard                             | 8980            | 30070  | 38119  | 47873  | 8       |
| findMechanismOfProposal                     | 635             | 2067   | 821    | 4747   | 3       |
| fundTreasury                                | 8086            | 45189  | 44726  | 65956  | 29      |
| fundingVote                                 | 1669            | 106859 | 106749 | 410840 | 275     |
| getDelegateReward                           | 3071            | 3561   | 3071   | 5113   | 5       |
| getDistributionId                           | 351             | 395    | 351    | 2351   | 667     |
| getDistributionPeriodInfo                   | 1059            | 1677   | 1059   | 5059   | 97      |
| getExtraordinaryProposalInfo                | 1029            | 1029   | 1029   | 1029   | 3       |
| getExtraordinaryProposalSucceeded           | 2290            | 2712   | 2788   | 3059   | 3       |
| getFundedProposalSlate                      | 1133            | 1309   | 1368   | 1368   | 4       |
| getFundingPowerVotes                        | 15480           | 15668  | 15731  | 15731  | 4       |
| getFundingVotesCast                         | 1601            | 2341   | 2341   | 3081   | 2       |
| getMinimumThresholdPercentage               | 493             | 1250   | 764    | 2493   | 3       |
| getProposalInfo                             | 1038            | 1038   | 1038   | 1038   | 110     |
| getSlateHash                                | 933             | 941    | 945    | 945    | 3       |
| getSliceOfNonTreasury                       | 1592            | 4842   | 4842   | 8092   | 2       |
| getSliceOfTreasury                          | 761             | 1761   | 1761   | 2761   | 2       |
| getTopTenProposals                          | 1164            | 2428   | 2340   | 3281   | 16      |
| getVoterInfo                                | 1078            | 1078   | 1078   | 1078   | 5       |
| getVotesExtraordinary                       | 810             | 7740   | 7775   | 8849   | 387     |
| getVotesFunding                             | 2467            | 6662   | 2875   | 11638  | 15      |
| getVotesScreening                           | 5338            | 5379   | 5372   | 6514   | 535     |
| hasVotedExtraordinary                       | 717             | 1717   | 1717   | 2717   | 2       |
| hashProposal                                | 3985            | 3985   | 3985   | 3985   | 95      |
| proposeExtraordinary                        | 4720            | 62347  | 82362  | 86701  | 17      |
| proposeStandard                             | 4676            | 79065  | 82557  | 83065  | 92      |
| screeningVote                               | 1950            | 52936  | 52419  | 470771 | 294     |
| screeningVotesCast                          | 675             | 1341   | 675    | 2675   | 3       |
| startNewDistributionPeriod                  | 629             | 48585  | 53223  | 75747  | 20      |
| state                                       | 1361            | 4599   | 4014   | 7412   | 20      |
| updateSlate                                 | 1002            | 56729  | 70091  | 290313 | 17      |
| voteExtraordinary                           | 571             | 29372  | 29599  | 31565  | 384     |
```

gas after
```
| Function Name                               | min             | avg    | median | max    | # calls |
| claimDelegateReward                         | 1407            | 58037  | 58540  | 65340  | 436     |
| executeExtraordinary                        | 7152            | 42738  | 39567  | 95588  | 7       |
| executeStandard                             | 8775            | 29860  | 37905  | 47659  | 8       |
| findMechanismOfProposal                     | 613             | 2043   | 799    | 4719   | 3       |
| fundTreasury                                | 8001            | 45104  | 44641  | 65872  | 29      |
| fundingVote                                 | 1584            | 106417 | 106376 | 409345 | 451     |
| getDelegateReward                           | 2975            | 3465   | 2975   | 5017   | 5       |
| getDistributionId                           | 374             | 404    | 374    | 2374   | 995     |
| getDistributionPeriodInfo                   | 1046            | 1867   | 1046   | 5046   | 73      |
| getExtraordinaryProposalInfo                | 992             | 992    | 992    | 992    | 3       |
| getExtraordinaryProposalSucceeded           | 2245            | 2664   | 2740   | 3008   | 3       |
| getFundedProposalSlate                      | 1133            | 1309   | 1368   | 1368   | 4       |
| getFundingPowerVotes                        | 15500           | 15688  | 15751  | 15751  | 4       |
| getFundingVotesCast                         | 1577            | 2317   | 2317   | 3057   | 2       |
| getMinimumThresholdPercentage               | 471             | 1227   | 739    | 2471   | 3       |
| getProposalInfo                             | 980             | 980    | 980    | 980    | 110     |
| getSlateHash                                | 872             | 880    | 884    | 884    | 3       |
| getSliceOfNonTreasury                       | 1577            | 4827   | 4827   | 8077   | 2       |
| getSliceOfTreasury                          | 781             | 1781   | 1781   | 2781   | 2       |
| getTopTenProposals                          | 1187            | 2451   | 2363   | 3304   | 16      |
| getVoterInfo                                | 1002            | 1002   | 1002   | 1002   | 5       |
| getVotesExtraordinary                       | 764             | 7644   | 7681   | 8755   | 363     |
| getVotesFunding                             | 2389            | 6565   | 2797   | 11518  | 15      |
| getVotesScreening                           | 5313            | 5351   | 5347   | 6489   | 887     |
| hasVotedExtraordinary                       | 683             | 1683   | 1683   | 2683   | 2       |
| hashProposal                                | 3843            | 3843   | 3843   | 3843   | 68      |
| proposeExtraordinary                        | 4497            | 57683  | 83926  | 86265  | 14      |
| proposeStandard                             | 4475            | 77505  | 82660  | 82660  | 68      |
| screeningVote                               | 1847            | 53908  | 52443  | 466426 | 470     |
| screeningVotesCast                          | 663             | 1329   | 663    | 2663   | 3       |
| startNewDistributionPeriod                  | 617             | 48521  | 53163  | 75597  | 20      |
| state                                       | 1337            | 4271   | 3838   | 7331   | 17      |
| updateSlate                                 | 971             | 56593  | 69994  | 289784 | 17      |
| voteExtraordinary                           | 565             | 29217  | 29458  | 31424  | 360     |
```

### CODE REVIEW

**Comment by grandizzy** [comment]
To be discussed if we want such or run with optimizer on

**Review by ith-harvey — APPROVED** [review]
LGTM

**Comment by MikeHathaway** [comment]
The gas impact is pretty minimal either way. Given the potential for bugs, it seems like we should definitely turn the optimizer off

**Comment by grandizzy** [comment]
> The gas impact is pretty minimal either way. Given the potential for bugs, it seems like we should definitely turn the optimizer off

kk, will make this ready for review again, need one more update in foundry.toml to turn it off for good

**Comment by grandizzy** [comment]
> > The gas impact is pretty minimal either way. Given the potential for bugs, it seems like we should definitely turn the optimizer off
> 
> kk, will make this ready for review again, need one more update in foundry.toml to turn it off for good

get that back, with `optimizer = false` option contract exceeds max size, so a no go
 `| GrantFund         | 33.264    | -8.688      |`

**Comment by grandizzy** [comment]
closing this as not possible, exceeds deployment size. we can look into bumping the optimizer runs from the default 200 and improve gas costs since disabling optimizer is not an option

**Pull request closed without merging**
