### PR TITLE
Remove EFM

### PR DESCRIPTION
**Pull request by MikeHathaway**
# Description of change
## High level
* Remove Extraordinary Funding Mechanism
  * No business logic changed. 
  * Update project structure, consolidating GrantFund, Funding, and StandardFunding into a single file.
  * Split different sections of the interface into individual interface files.
  * Rename "QuarterlyDistribution" -> "DistributionPeriod"
  * Rename "executeStandard" -> "execute" and "proposeStandard" -> "propose" (increasing compliance with other governance interface specs)
* Add additional invariants to standard funding inspired by removed extraordinary invariants.

# Description of bug or vulnerability and solution
* Due to several bugs that were mentioned in C4 reports and the team's opinion of EFMs value to the protocol this feature is being cut.

# Contract size
## Pre Change
<PASTE_OUTPUT_HERE>
## Post Change
`| GrantFund             | 16.224    | 8.352       |`

### CODE REVIEW

**Review by ith-harvey — CHANGES_REQUESTED** [review]
`GRANT_FUND.md`, `IGrantFundActions.sol`, `IGrantFundState.sol` still have references to extraordinary

**Review by ith-harvey — APPROVED** [review]

**Comment by ith-harvey** [comment]
> `GRANT_FUND.md`, `IGrantFundActions.sol`, `IGrantFundState.sol` still have references to extraordinary

resolved in -> https://github.com/ajna-finance/ecosystem-coordination/pull/91/commits/a9032b8f47cf5018e2ae098268718f49d3cf0655

**Comment by EdNoepel** [comment]
Unrelated to these changes, but if we're making a huge change like this, can we also resolve the compilation warnings?

image

**Review by EdNoepel — COMMENTED** [review]
`GrantFund.jpg` still references the EFM.
`README.md` still references _Funding.sol_.
Otherwise looks good.

**Comment by ith-harvey** [comment]
> 

resolved readme issue -> https://github.com/ajna-finance/ecosystem-coordination/pull/91/commits/a4305cc7d6db0c2ced3eac6da20a541d1e6f2561

@MikeHathaway I don't have the diagram handy... can you update the jpeg?

**Comment by MikeHathaway** [comment]
> Unrelated to these changes, but if we're making a huge change like this, can we also resolve the compilation warnings?
> 
> 
> 
> image
> 
> 
I'll fix that happy path warning, but won't be able to fix the other compilation warning unless we upgrade to sol 0.8.18

**Comment by grandizzy** [comment]
> > Unrelated to these changes, but if we're making a huge change like this, can we also resolve the compilation warnings?
> > image
> 
> I'll fix that happy path warning, but won't be able to fix the other compilation warning unless we upgrade to sol 0.8.18

I thought we're already using sol 0.8.18?

**Review by prat-gpt — APPROVED** [review]
l have added a PR on top of this PR here #93, removing description prefix. rest lgtm.

**Comment by grandizzy** [comment]
> > Unrelated to these changes, but if we're making a huge change like this, can we also resolve the compilation warnings?
> > image
> 
> I'll fix that happy path warning, but won't be able to fix the other compilation warning unless we upgrade to sol 0.8.18

ah, to fix `block.prevrandao`, just add `FOUNDRY_EVM_VERSION = paris` in your .env file

**Review by grandizzy — COMMENTED** [review]
tidy, looks good! good to go after merging https://github.com/ajna-finance/ecosystem-coordination/pull/93

**Pull request merged**
