### PR TITLE
Deployment scripts for Mainnet, Kovan and Rinkeby

### PR DESCRIPTION
**Pull request by ith-harvey**
* Adjusted `Makefile` to include commands for: `deploy-rinkeby`, `deploy-mainnet`, `deploy-kovan`
* Polished deployment script of `AjnaToken.s.sol` allowed for passing of arguments.

### CODE REVIEW

**Review by grandizzy — CHANGES_REQUESTED** [review]
LGTM! great to see forge script leveraged here
2 comments from my side:
- not sure we need 3 targets for deployment, but only one and have a generic `${RPC_URL}` var similar with the `${PRIVATE_KEY}` one that is specified? (I mean we don't have `${RINKEBY_PRIVATE_KEY}` `${KOVAN_PRIVATE_KEY}` `${MAINNET_PRIVATE_KEY}` but only the `${PRIVATE_KEY}` which I think is good, same should be for RPC URL IMO)
- can you please update README with a `Deployment` section?

**Comment by ith-harvey** [comment]
> LGTM! great to see forge script leveraged here 2 comments from my side:
> 
> * not sure we need 3 targets for deployment, but only one and have a generic `${RPC_URL}` var similar with the `${PRIVATE_KEY}` one that is specified? (I mean we don't have `${RINKEBY_PRIVATE_KEY}` `${KOVAN_PRIVATE_KEY}` `${MAINNET_PRIVATE_KEY}` but only the `${PRIVATE_KEY}` which I think is good, same should be for RPC URL IMO)
> * can you please update README with a `Deployment` section?

Updated : )

**Comment by grandizzy** [comment]
> > LGTM! great to see forge script leveraged here 2 comments from my side:
> > 
> > * not sure we need 3 targets for deployment, but only one and have a generic `${RPC_URL}` var similar with the `${PRIVATE_KEY}` one that is specified? (I mean we don't have `${RINKEBY_PRIVATE_KEY}` `${KOVAN_PRIVATE_KEY}` `${MAINNET_PRIVATE_KEY}` but only the `${PRIVATE_KEY}` which I think is good, same should be for RPC URL IMO)
> > * can you please update README with a `Deployment` section?
> 
> Updated : )

Thank you! Since token contract now receives minter address in constructor, is there any way to pass such from CLI to forge Solidity script? (I wasn't able to find how to do this, of course we can hardcode the address directly in `AjnaToken.s.sol` but this will break deployments on testnets...)

**Comment by ith-harvey** [comment]
> > > LGTM! great to see forge script leveraged here 2 comments from my side:
> > > 
> > > * not sure we need 3 targets for deployment, but only one and have a generic `${RPC_URL}` var similar with the `${PRIVATE_KEY}` one that is specified? (I mean we don't have `${RINKEBY_PRIVATE_KEY}` `${KOVAN_PRIVATE_KEY}` `${MAINNET_PRIVATE_KEY}` but only the `${PRIVATE_KEY}` which I think is good, same should be for RPC URL IMO)
> > > * can you please update README with a `Deployment` section?
> > 
> > 
> > Updated : )
> 
> Thank you! Since token contract now receives minter address in constructor, is there any way to pass such from CLI to forge Solidity script? (I wasn't able to find how to do this, of course we can hardcode the address directly in `AjnaToken.s.sol` but this will break deployments on testnets...)

Thanks George, yep. Resolved here -> https://github.com/ajna-finance/ajna-token/pull/10/commits/900d887b4a2d932f2215fdc3dbe892ecaa6526a2

Proof: https://kovan.etherscan.io/tx/0x9f4d48f2a837d4e88a09e56065097eaf197171574ab9a8723faf26b1aa9dddd9

**Comment by grandizzy** [comment]
> > > > LGTM! great to see forge script leveraged here 2 comments from my side:
> > > > 
> > > > * not sure we need 3 targets for deployment, but only one and have a generic `${RPC_URL}` var similar with the `${PRIVATE_KEY}` one that is specified? (I mean we don't have `${RINKEBY_PRIVATE_KEY}` `${KOVAN_PRIVATE_KEY}` `${MAINNET_PRIVATE_KEY}` but only the `${PRIVATE_KEY}` which I think is good, same should be for RPC URL IMO)
> > > > * can you please update README with a `Deployment` section?
> > > 
> > > 
> > > Updated : )
> > 
> > 
> > Thank you! Since token contract now receives minter address in constructor, is there any way to pass such from CLI to forge Solidity script? (I wasn't able to find how to do this, of course we can hardcode the address directly in `AjnaToken.s.sol` but this will break deployments on testnets...)
> 
> Thanks George, yep. Resolved here -> [900d887](https://github.com/ajna-finance/ajna-token/commit/900d887b4a2d932f2215fdc3dbe892ecaa6526a2)
> 
> Proof: https://kovan.etherscan.io/tx/0x9f4d48f2a837d4e88a09e56065097eaf197171574ab9a8723faf26b1aa9dddd9

Awesome! Learned something new - `vm.envAddress` :) thanks

**Review by grandizzy — APPROVED** [review]
LGTM!

**Pull request merged**
